version: '3.7'
services:
  image-api:
    healthcheck:
      test: ["CMD", "curl", "-XGET", "--show-error", "--fail", "http://localhost:3000/ping"]
      interval: 2s
      retries: 2
      start_period: 3s
      timeout: 3s
