version: '3.7'
services:
  image-api:
    image: hunguyen/niotd-api:latest
    environment:
      - RAILS_ENV=development
    networks:
      niotd-network:
    entrypoint: ["/app/entrypoint.sh"]
  front-web:
    image: nginx:1.19.8
    networks:
      niotd-network:
  mysql:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - niotd-data:/var/lib/mysql
    networks:
      niotd-network:

networks:
  niotd-network:

volumes:
  niotd-data:
