configs:
  front-web-css:
    external: true
    name: front-web-css
  front-web-index:
    external: true
    name: front-web-index
  front-web-template:
    external: true
    name: front-web-template
  image-api-setting:
    external: true
    name: image-api-setting
networks:
  niotd-network: {}
secrets:
  image-api-db-config:
    external: true
    name: image-api-db-config
  image-api-setting:
    external: true
    name: image-api-setting
services:
  front-web:
    configs:
    - source: front-web-css
      target: /app/index.css
    - source: front-web-index
      target: /app/index.html
    - source: front-web-template
      target: /etc/nginx/templates/default.conf.template
    image: nginx:1.19.8
    networks:
      niotd-network: {}
    ports:
      - 80:80
  image-api:
    configs:
    - source: image-api-setting
      target: /app/config/settings.yml
    deploy:
      replicas: 6
      rollback_config:
        failure_action: continue
        order: start-first
        parallelism: 6
      update_config:
        failure_action: rollback
        monitor: 60s
        order: start-first
        parallelism: 3
    entrypoint:
    - /app/entrypoint.sh
    environment:
      RAILS_ENV: development
#    healthcheck:
#      interval: 2s
#      retries: 2
#      start_period: 3s
#      test:
#      - CMD
#      - curl
#      - -XGET
#      - --show-error
#      - --fail
#      - http://localhost:3000/ping
#      timeout: 3s
    image: hunguyen/niotd-api:latest
    networks:
      niotd-network: {}
    secrets:
    - source: image-api-db-config
      target: /app/config/database.yml
    - source: image-api-setting
      target: /app/config/settings/development.yml
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      placement:
        constraints:
        - node.labels.role==database
    environment:
      MYSQL_ROOT_PASSWORD: '123'
    image: mysql:5.7.29
    networks:
      niotd-network: {}
    volumes:
    - niotd-data:/var/lib/mysql:rw
version: '3.7'
volumes:
  niotd-data: {}

